import { Dimensions, StyleSheet } from "react-native";
import { BorderRadius, Spacing, Typography } from "../../styles/theme";

const { width } = Dimensions.get("window");

export const createStyles = (colors) =>
    StyleSheet.create({
        container: { flex: 1, backgroundColor: colors.background },
        loadingContainer: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: colors.background,
        },
        errorText: { ...Typography.body, color: colors.textSecondary },
        imageContainer: { position: "relative" },
        heroImage: { width, height: width * 0.75, backgroundColor: colors.skeleton },
        backButton: {
            position: "absolute",
            top: 50,
            left: Spacing.md,
            backgroundColor: "rgba(0,0,0,0.4)",
            borderRadius: BorderRadius.full,
            padding: Spacing.sm,
        },
        topRightButtons: { position: "absolute", top: 50, right: Spacing.md, flexDirection: "row", gap: Spacing.sm },
        iconButton: { backgroundColor: "rgba(0,0,0,0.4)", borderRadius: BorderRadius.full, padding: Spacing.sm },
        content: { padding: Spacing.lg },
        title: { ...Typography.h1, color: colors.text, marginBottom: Spacing.xs },
        authorRow: { flexDirection: "row", alignItems: "center", gap: Spacing.xs, marginBottom: Spacing.md },
        authorText: { ...Typography.bodySmall, color: colors.textSecondary },
        metaRow: { flexDirection: "row", gap: Spacing.lg, marginBottom: Spacing.lg },
        metaItem: { flexDirection: "row", alignItems: "center", gap: Spacing.xs },
        metaText: { ...Typography.bodySmall, color: colors.textSecondary },
        portionContainer: {
            backgroundColor: colors.surfaceVariant,
            borderRadius: BorderRadius.md,
            padding: Spacing.md,
            marginBottom: Spacing.lg,
            alignItems: "center",
        },
        portionLabel: {
            ...Typography.bodySmall,
            color: colors.textSecondary,
            fontWeight: "600",
            marginBottom: Spacing.sm,
            textTransform: "uppercase",
            letterSpacing: 1,
        },
        portionControls: { flexDirection: "row", alignItems: "center", gap: Spacing.lg },
        portionButton: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: colors.surface,
            borderWidth: 2,
            borderColor: colors.primary,
            alignItems: "center",
            justifyContent: "center",
        },
        portionButtonDisabled: { borderColor: colors.border, backgroundColor: colors.surfaceVariant },
        portionValueContainer: { alignItems: "center", minWidth: 60 },
        portionValue: { ...Typography.h1, color: colors.primary },
        portionUnit: { ...Typography.caption, color: colors.textSecondary },
        resetText: { ...Typography.caption, color: colors.primary, marginTop: Spacing.sm, fontWeight: "600" },
        nutritionRow: {
            flexDirection: "row",
            justifyContent: "space-around",
            backgroundColor: colors.surfaceVariant,
            borderRadius: BorderRadius.md,
            paddingVertical: Spacing.md,
            marginBottom: Spacing.lg,
        },
        nutritionItem: { alignItems: "center" },
        nutritionValue: { ...Typography.h3, color: colors.text },
        nutritionLabel: { ...Typography.caption, color: colors.textSecondary, textTransform: "capitalize" },
        tabRow: {
            flexDirection: "row",
            marginBottom: Spacing.md,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
        },
        tab: { flex: 1, paddingVertical: Spacing.sm, alignItems: "center" },
        tabActive: { borderBottomWidth: 2, borderBottomColor: colors.primary },
        tabText: { ...Typography.button, color: colors.textSecondary },
        tabTextActive: { color: colors.primary },
        section: { marginBottom: Spacing.lg },
        ingredientRow: {
            flexDirection: "row",
            alignItems: "center",
            paddingVertical: Spacing.sm,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
        },
        ingredientDot: {
            width: 8,
            height: 8,
            borderRadius: 4,
            backgroundColor: colors.primary,
            marginRight: Spacing.md,
        },
        ingredientText: { ...Typography.body, color: colors.text, flex: 1 },
        ingredientAmount: { fontWeight: "700", color: colors.primary },
        addToCartButton: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: Spacing.sm,
            backgroundColor: colors.primary,
            borderRadius: BorderRadius.sm,
            paddingVertical: 14,
            marginTop: Spacing.md,
        },
        addToCartText: { ...Typography.button, color: colors.textInverse },
        stepRow: { flexDirection: "row", marginBottom: Spacing.md, gap: Spacing.md },
        stepNumber: {
            width: 28,
            height: 28,
            borderRadius: 14,
            backgroundColor: colors.primary,
            alignItems: "center",
            justifyContent: "center",
            marginTop: 2,
        },
        stepNumberText: { ...Typography.bodySmall, color: colors.textInverse, fontWeight: "700" },
        stepText: { ...Typography.body, color: colors.text, flex: 1, lineHeight: 24 },
        ratingSection: {
            alignItems: "center",
            paddingVertical: Spacing.lg,
            borderTopWidth: 1,
            borderTopColor: colors.border,
        },
        sectionTitle: { ...Typography.h3, color: colors.text, marginBottom: Spacing.md },
        commentsSection: { paddingTop: Spacing.md },
        commentCard: {
            backgroundColor: colors.surfaceVariant,
            borderRadius: BorderRadius.sm,
            padding: Spacing.md,
            marginBottom: Spacing.sm,
        },
        commentText: { ...Typography.bodySmall, color: colors.text, marginTop: Spacing.xs },
        deleteButton: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: Spacing.sm,
            paddingVertical: Spacing.md,
            borderRadius: BorderRadius.sm,
            borderWidth: 1,
            borderColor: "#FF4444",
            marginTop: Spacing.xl,
            marginBottom: Spacing.xxl,
        },
        deleteButtonText: { ...Typography.button, color: "#FF4444" },
    });
