import { StyleSheet } from "react-native";
import { BorderRadius, Spacing, Typography } from "../../styles/theme";

export const createStyles = (colors) =>
    StyleSheet.create({
        container: { flex: 1, backgroundColor: colors.background },
        content: { padding: Spacing.lg, paddingBottom: Spacing.xxl * 2 },
        header: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            marginBottom: Spacing.lg,
        },
        headerTitle: { ...Typography.h2, color: colors.text },
        label: {
            ...Typography.bodySmall,
            color: colors.textSecondary,
            fontWeight: "600",
            marginBottom: Spacing.xs,
            marginTop: Spacing.md,
        },
        input: {
            backgroundColor: colors.surfaceVariant,
            borderRadius: BorderRadius.sm,
            paddingHorizontal: Spacing.md,
            paddingVertical: 12,
            ...Typography.body,
            color: colors.text,
            borderWidth: 1,
            borderColor: colors.border,
        },
        categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: Spacing.sm, marginTop: Spacing.xs },
        categoryChip: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            paddingHorizontal: Spacing.md,
            paddingVertical: Spacing.sm,
            borderRadius: BorderRadius.full,
            borderWidth: 1,
            borderColor: colors.border,
            backgroundColor: colors.surface,
        },
        categoryChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
        categoryChipText: { ...Typography.caption, color: colors.text, fontWeight: "600" },
        categoryChipTextActive: { color: colors.textInverse },
        row: { flexDirection: "row", gap: Spacing.md },
        halfField: { flex: 1 },
        sectionHeader: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            marginTop: Spacing.lg,
            marginBottom: Spacing.sm,
        },
        sectionTitle: { ...Typography.h3, color: colors.text, marginTop: Spacing.lg },
        sectionHint: { ...Typography.caption, color: colors.textSecondary, marginBottom: Spacing.sm },
        addRowButton: { padding: Spacing.xs },
        ingredientRow: { flexDirection: "row", alignItems: "center", gap: Spacing.sm, marginBottom: Spacing.sm },
        ingredientAmount: { width: 60, textAlign: "center" },
        ingredientUnit: { width: 70 },
        ingredientName: { flex: 1 },
        stepRow: { flexDirection: "row", alignItems: "flex-start", gap: Spacing.sm, marginBottom: Spacing.sm },
        stepNumberBadge: {
            width: 28,
            height: 28,
            borderRadius: 14,
            backgroundColor: colors.primary,
            alignItems: "center",
            justifyContent: "center",
            marginTop: 10,
        },
        stepNumberText: { ...Typography.bodySmall, color: colors.textInverse, fontWeight: "700" },
        stepInput: { flex: 1, minHeight: 48, textAlignVertical: "top" },
        nutritionGrid: { flexDirection: "row", flexWrap: "wrap", gap: Spacing.sm, marginTop: Spacing.sm },
        nutritionField: { width: "48%" },
        nutritionLabel: { ...Typography.caption, color: colors.textSecondary, marginBottom: 4 },
        nutritionInput: {
            backgroundColor: colors.surfaceVariant,
            borderRadius: BorderRadius.sm,
            paddingHorizontal: Spacing.md,
            paddingVertical: 10,
            ...Typography.body,
            color: colors.text,
            borderWidth: 1,
            borderColor: colors.border,
            textAlign: "center",
        },
        submitButton: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: Spacing.sm,
            backgroundColor: colors.primary,
            borderRadius: BorderRadius.sm,
            paddingVertical: 16,
            marginTop: Spacing.xl,
        },
        submitButtonDisabled: { opacity: 0.7 },
        submitButtonText: { ...Typography.button, color: colors.textInverse },
    });
